export function generateEula(accepted: boolean): string {
  return (
    [
      '#By changing the setting below to TRUE you are indicating your agreement to our EULA (https://aka.ms/MinecraftEULA).',
      `#Generated by Blossom on ${new Date().toISOString()}`,
      `eula=${accepted}`
    ].join('\n') + '\n'
  )
}
