import type { WizardAnswers } from '@shared/wizardConfig'

const WORLD_TYPE_MAP: Record<string, string> = {
  default: 'minecraft:normal',
  flat: 'minecraft:flat',
  large_biomes: 'minecraft:large_biomes',
  amplified: 'minecraft:amplified'
}

export function generateServerProperties(answers: WizardAnswers): string {
  const identity = answers.serverIdentity
  const world = answers.worldSettings
  const networking = answers.networking

  const properties: [string, string][] = [
    ['motd', identity.motd ?? 'A Minecraft Server'],
    ['max-players', String(identity.maxPlayers ?? 20)],
    ['difficulty', identity.difficulty ?? 'easy'],
    ['gamemode', identity.gamemode ?? 'survival'],
    ['hardcore', String(identity.hardcore ?? false)],
    ['pvp', String(identity.pvp ?? true)],
    ['white-list', String(identity.whitelist ?? false)],
    ['level-type', WORLD_TYPE_MAP[world.worldType ?? 'default']],
    ['level-name', 'world'],
    ['level-seed', world.seed ?? ''],
    ['generate-structures', String(world.generateStructures ?? true)],
    ['view-distance', String(world.viewDistance ?? 10)],
    ['simulation-distance', String(world.simulationDistance ?? 10)],
    ['spawn-protection', String(world.spawnProtection ?? 16)],
    ['server-port', String(networking.serverPort ?? 25565)],
    ['online-mode', String(networking.onlineMode ?? true)],
    ['enable-command-block', 'false'],
    ['allow-flight', 'false'],
    ['resource-pack', ''],
    ['network-compression-threshold', '256']
  ]

  const header = `#Minecraft server properties\n#Generated by Blossom on ${new Date().toISOString()}\n`
  const body = properties.map(([key, value]) => `${key}=${value}`).join('\n')

  return `${header}${body}\n`
}
