export interface ReadmeParams {
  projectName: string
  softwareName: string
  minecraftVersion: string
  serverPort: number
  installedAddons?: { name: string; folder: 'plugins' | 'mods' }[]
}

export function generateReadme(params: ReadmeParams): string {
  const addons = params.installedAddons ?? []
  const addonFolder = addons[0]?.folder ?? 'plugins'
  const addonsSection =
    addons.length > 0
      ? `\n## Installed ${addonFolder}\n\n${addons.map((addon) => `- ${addon.name}`).join('\n')}\n`
      : ''

  return `# ${params.projectName}

Generated by Blossom.

## What's in this folder

- \`server.jar\` — the ${params.softwareName} server for Minecraft ${params.minecraftVersion}
- \`server.properties\` — your server configuration
- \`eula.txt\` — your acceptance of Mojang's EULA
- \`start.bat\` / \`start.sh\` — scripts to launch the server on Windows / Linux${
    addons.length > 0 ? `\n- \`${addonFolder}/\` — your selected ${addonFolder}` : ''
  }
${addonsSection}
## Running locally (Windows)

Double-click \`start.bat\`. Java must be installed on this machine.

## Uploading to a VPS (Linux)

1. Upload this entire folder to your server.
2. Make the start script executable: \`chmod +x start.sh\`
3. Run it: \`./start.sh\`

Make sure Java is installed on the host (\`java -version\`).

## Connecting

Default port: ${params.serverPort}. Share your server's IP (and port, if not 25565) with your friends.
`
}
